name: apka
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+16

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.6
  google_fonts: ^6.2.1
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.4.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1
  connectivity_plus: ^6.1.4
  android_intent_plus: ^5.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  app_settings: ^6.1.1
  confetti: ^0.8.0
  in_app_purchase: ^3.2.3
  firebase_app_check: ^0.3.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/Fotos/
    - assets/data/
    - assets/quotes.json
    - assets/weekly_content.json
    - assets/Icon.png
    - assets/Logo.png
    - assets/Aneta.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/Logo.png"